services:
  homebridge:
    image: homebridge/homebridge:latest
    restart: always
    network_mode: host
    volumes:
      - ./volumes/homebridge:/homebridge
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"
  mongo:
    image: mongo:4.1.13-bionic
    restart: always
    ports:
      - 27018:27017
